// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package enter

import (
	"game/api/enter"
)

type ControllerV1 struct{}

func NewV1() enter.IEnterV1 {
	return &ControllerV1{}
}
