// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package controller

import (
	v1 "gfast/api/v1"
)

type ControllerSet struct{}

func NewSet() v1.IV1Set {
	return &ControllerSet{}
}
