// protoc --go_out=plugins=grpc:. *.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.9
// source: set_game/v1/set.proto

package v1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SetGame_SendSet_FullMethodName = "/set_game.v1.SetGame/SendSet"
)

// SetGameClient is the client API for SetGame service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SetGameClient interface {
	SendSet(ctx context.Context, in *SendSetReq, opts ...grpc.CallOption) (*SendSetRes, error)
}

type setGameClient struct {
	cc grpc.ClientConnInterface
}

func NewSetGameClient(cc grpc.ClientConnInterface) SetGameClient {
	return &setGameClient{cc}
}

func (c *setGameClient) SendSet(ctx context.Context, in *SendSetReq, opts ...grpc.CallOption) (*SendSetRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendSetRes)
	err := c.cc.Invoke(ctx, SetGame_SendSet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SetGameServer is the server API for SetGame service.
// All implementations must embed UnimplementedSetGameServer
// for forward compatibility.
type SetGameServer interface {
	SendSet(context.Context, *SendSetReq) (*SendSetRes, error)
	mustEmbedUnimplementedSetGameServer()
}

// UnimplementedSetGameServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSetGameServer struct{}

func (UnimplementedSetGameServer) SendSet(context.Context, *SendSetReq) (*SendSetRes, error) {
	return nil, status.Error(codes.Unimplemented, "method SendSet not implemented")
}
func (UnimplementedSetGameServer) mustEmbedUnimplementedSetGameServer() {}
func (UnimplementedSetGameServer) testEmbeddedByValue()                 {}

// UnsafeSetGameServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SetGameServer will
// result in compilation errors.
type UnsafeSetGameServer interface {
	mustEmbedUnimplementedSetGameServer()
}

func RegisterSetGameServer(s grpc.ServiceRegistrar, srv SetGameServer) {
	// If the following call panics, it indicates UnimplementedSetGameServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SetGame_ServiceDesc, srv)
}

func _SetGame_SendSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendSetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SetGameServer).SendSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SetGame_SendSet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SetGameServer).SendSet(ctx, req.(*SendSetReq))
	}
	return interceptor(ctx, in, info, handler)
}

// SetGame_ServiceDesc is the grpc.ServiceDesc for SetGame service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SetGame_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "set_game.v1.SetGame",
	HandlerType: (*SetGameServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendSet",
			Handler:    _SetGame_SendSet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "set_game/v1/set.proto",
}
