// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package set

import (
	"api-service/api/set"
)

type ControllerV1 struct{}

func NewV1() set.ISetV1 {
	return &ControllerV1{}
}
