# CLI.
gfcli:
  gen:
    dao:
      - link:            "mysql:root:Rwr!124124@tcp(8.155.147.137:3306)/max2"
        tables:          "set_game"
        removePrefix:    "m2_"
        descriptionTag:  true
        noModelComment:  true
        path: "./internal/app/set"