// protoc --go_out=plugins=grpc:. *.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.9
// source: login_game/v1/login_game.proto

package v1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendLoginReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty" v:"required"`     // v: required
	UserName      string                 `protobuf:"bytes,2,opt,name=UserName,proto3" json:"UserName,omitempty" v:"required"` // v: required
	Token         string                 `protobuf:"bytes,3,opt,name=Token,proto3" json:"Token,omitempty" v:"required"`       // v: required
	Point         string                 `protobuf:"bytes,4,opt,name=Point,proto3" json:"Point,omitempty" v:"required"`       // v: required
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendLoginReq) Reset() {
	*x = SendLoginReq{}
	mi := &file_login_game_v1_login_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendLoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendLoginReq) ProtoMessage() {}

func (x *SendLoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_login_game_v1_login_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendLoginReq.ProtoReflect.Descriptor instead.
func (*SendLoginReq) Descriptor() ([]byte, []int) {
	return file_login_game_v1_login_game_proto_rawDescGZIP(), []int{0}
}

func (x *SendLoginReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SendLoginReq) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *SendLoginReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *SendLoginReq) GetPoint() string {
	if x != nil {
		return x.Point
	}
	return ""
}

type SendLoginRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendLoginRes) Reset() {
	*x = SendLoginRes{}
	mi := &file_login_game_v1_login_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendLoginRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendLoginRes) ProtoMessage() {}

func (x *SendLoginRes) ProtoReflect() protoreflect.Message {
	mi := &file_login_game_v1_login_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendLoginRes.ProtoReflect.Descriptor instead.
func (*SendLoginRes) Descriptor() ([]byte, []int) {
	return file_login_game_v1_login_game_proto_rawDescGZIP(), []int{1}
}

var File_login_game_v1_login_game_proto protoreflect.FileDescriptor

const file_login_game_v1_login_game_proto_rawDesc = "" +
	"\n" +
	"\x1elogin_game/v1/login_game.proto\x12\rlogin_game.v1\"n\n" +
	"\fSendLoginReq\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\tR\x06UserId\x12\x1a\n" +
	"\bUserName\x18\x02 \x01(\tR\bUserName\x12\x14\n" +
	"\x05Token\x18\x03 \x01(\tR\x05Token\x12\x14\n" +
	"\x05Point\x18\x04 \x01(\tR\x05Point\"\x0e\n" +
	"\fSendLoginRes2T\n" +
	"\tLoginGame\x12G\n" +
	"\tSendLogin\x12\x1b.login_game.v1.SendLoginReq\x1a\x1b.login_game.v1.SendLoginRes\"\x00B\x16Z\x14api/login_game/v1;v1b\x06proto3"

var (
	file_login_game_v1_login_game_proto_rawDescOnce sync.Once
	file_login_game_v1_login_game_proto_rawDescData []byte
)

func file_login_game_v1_login_game_proto_rawDescGZIP() []byte {
	file_login_game_v1_login_game_proto_rawDescOnce.Do(func() {
		file_login_game_v1_login_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_login_game_v1_login_game_proto_rawDesc), len(file_login_game_v1_login_game_proto_rawDesc)))
	})
	return file_login_game_v1_login_game_proto_rawDescData
}

var file_login_game_v1_login_game_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_login_game_v1_login_game_proto_goTypes = []any{
	(*SendLoginReq)(nil), // 0: login_game.v1.SendLoginReq
	(*SendLoginRes)(nil), // 1: login_game.v1.SendLoginRes
}
var file_login_game_v1_login_game_proto_depIdxs = []int32{
	0, // 0: login_game.v1.LoginGame.SendLogin:input_type -> login_game.v1.SendLoginReq
	1, // 1: login_game.v1.LoginGame.SendLogin:output_type -> login_game.v1.SendLoginRes
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_login_game_v1_login_game_proto_init() }
func file_login_game_v1_login_game_proto_init() {
	if File_login_game_v1_login_game_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_login_game_v1_login_game_proto_rawDesc), len(file_login_game_v1_login_game_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_login_game_v1_login_game_proto_goTypes,
		DependencyIndexes: file_login_game_v1_login_game_proto_depIdxs,
		MessageInfos:      file_login_game_v1_login_game_proto_msgTypes,
	}.Build()
	File_login_game_v1_login_game_proto = out.File
	file_login_game_v1_login_game_proto_goTypes = nil
	file_login_game_v1_login_game_proto_depIdxs = nil
}
