// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package register

import (
	"user/api/register"
)

type ControllerV1 struct{}

func NewV1() register.IRegisterV1 {
	return &ControllerV1{}
}
