// protoc --go_out=plugins=grpc:. *.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.9
// source: action/v1/action.proto

package v1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendActionReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Data          string                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	From          string                 `protobuf:"bytes,3,opt,name=from,proto3" json:"from,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendActionReq) Reset() {
	*x = SendActionReq{}
	mi := &file_action_v1_action_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendActionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendActionReq) ProtoMessage() {}

func (x *SendActionReq) ProtoReflect() protoreflect.Message {
	mi := &file_action_v1_action_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendActionReq.ProtoReflect.Descriptor instead.
func (*SendActionReq) Descriptor() ([]byte, []int) {
	return file_action_v1_action_proto_rawDescGZIP(), []int{0}
}

func (x *SendActionReq) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SendActionReq) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *SendActionReq) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

type SendActionRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendActionRes) Reset() {
	*x = SendActionRes{}
	mi := &file_action_v1_action_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendActionRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendActionRes) ProtoMessage() {}

func (x *SendActionRes) ProtoReflect() protoreflect.Message {
	mi := &file_action_v1_action_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendActionRes.ProtoReflect.Descriptor instead.
func (*SendActionRes) Descriptor() ([]byte, []int) {
	return file_action_v1_action_proto_rawDescGZIP(), []int{1}
}

var File_action_v1_action_proto protoreflect.FileDescriptor

const file_action_v1_action_proto_rawDesc = "" +
	"\n" +
	"\x16action/v1/action.proto\x12\taction.v1\"K\n" +
	"\rSendActionReq\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04data\x18\x02 \x01(\tR\x04data\x12\x12\n" +
	"\x04from\x18\x03 \x01(\tR\x04from\"\x0f\n" +
	"\rSendActionRes2L\n" +
	"\x06Action\x12B\n" +
	"\n" +
	"SendAction\x12\x18.action.v1.SendActionReq\x1a\x18.action.v1.SendActionRes\"\x00B\x12Z\x10api/action/v1;v1b\x06proto3"

var (
	file_action_v1_action_proto_rawDescOnce sync.Once
	file_action_v1_action_proto_rawDescData []byte
)

func file_action_v1_action_proto_rawDescGZIP() []byte {
	file_action_v1_action_proto_rawDescOnce.Do(func() {
		file_action_v1_action_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_action_v1_action_proto_rawDesc), len(file_action_v1_action_proto_rawDesc)))
	})
	return file_action_v1_action_proto_rawDescData
}

var file_action_v1_action_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_action_v1_action_proto_goTypes = []any{
	(*SendActionReq)(nil), // 0: action.v1.SendActionReq
	(*SendActionRes)(nil), // 1: action.v1.SendActionRes
}
var file_action_v1_action_proto_depIdxs = []int32{
	0, // 0: action.v1.Action.SendAction:input_type -> action.v1.SendActionReq
	1, // 1: action.v1.Action.SendAction:output_type -> action.v1.SendActionRes
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_action_v1_action_proto_init() }
func file_action_v1_action_proto_init() {
	if File_action_v1_action_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_action_v1_action_proto_rawDesc), len(file_action_v1_action_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_action_v1_action_proto_goTypes,
		DependencyIndexes: file_action_v1_action_proto_depIdxs,
		MessageInfos:      file_action_v1_action_proto_msgTypes,
	}.Build()
	File_action_v1_action_proto = out.File
	file_action_v1_action_proto_goTypes = nil
	file_action_v1_action_proto_depIdxs = nil
}
