// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package controller

import (
	v1 "gfast/api/v1"
)

type ControllerLog struct{}

func NewLog() v1.IV1Log {
	return &ControllerLog{}
}
