// protoc --go_out=plugins=grpc:. *.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.9
// source: login_game/v1/login.proto

package v1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LoginGame_SendLogin_FullMethodName = "/login_game.v1.LoginGame/SendLogin"
)

// LoginGameClient is the client API for LoginGame service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LoginGameClient interface {
	SendLogin(ctx context.Context, in *SendLoginReq, opts ...grpc.CallOption) (*SendLoginRes, error)
}

type loginGameClient struct {
	cc grpc.ClientConnInterface
}

func NewLoginGameClient(cc grpc.ClientConnInterface) LoginGameClient {
	return &loginGameClient{cc}
}

func (c *loginGameClient) SendLogin(ctx context.Context, in *SendLoginReq, opts ...grpc.CallOption) (*SendLoginRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendLoginRes)
	err := c.cc.Invoke(ctx, LoginGame_SendLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LoginGameServer is the server API for LoginGame service.
// All implementations must embed UnimplementedLoginGameServer
// for forward compatibility.
type LoginGameServer interface {
	SendLogin(context.Context, *SendLoginReq) (*SendLoginRes, error)
	mustEmbedUnimplementedLoginGameServer()
}

// UnimplementedLoginGameServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLoginGameServer struct{}

func (UnimplementedLoginGameServer) SendLogin(context.Context, *SendLoginReq) (*SendLoginRes, error) {
	return nil, status.Error(codes.Unimplemented, "method SendLogin not implemented")
}
func (UnimplementedLoginGameServer) mustEmbedUnimplementedLoginGameServer() {}
func (UnimplementedLoginGameServer) testEmbeddedByValue()                   {}

// UnsafeLoginGameServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LoginGameServer will
// result in compilation errors.
type UnsafeLoginGameServer interface {
	mustEmbedUnimplementedLoginGameServer()
}

func RegisterLoginGameServer(s grpc.ServiceRegistrar, srv LoginGameServer) {
	// If the following call panics, it indicates UnimplementedLoginGameServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LoginGame_ServiceDesc, srv)
}

func _LoginGame_SendLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendLoginReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoginGameServer).SendLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoginGame_SendLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoginGameServer).SendLogin(ctx, req.(*SendLoginReq))
	}
	return interceptor(ctx, in, info, handler)
}

// LoginGame_ServiceDesc is the grpc.ServiceDesc for LoginGame service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LoginGame_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "login_game.v1.LoginGame",
	HandlerType: (*LoginGameServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendLogin",
			Handler:    _LoginGame_SendLogin_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "login_game/v1/login.proto",
}
