// protoc --go_out=plugins=grpc:. *.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.9
// source: log_game/v1/log_game.proto

package v1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LogGame_SendLog_FullMethodName = "/log_game.v1.LogGame/SendLog"
)

// LogGameClient is the client API for LogGame service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LogGameClient interface {
	SendLog(ctx context.Context, in *SendLogReq, opts ...grpc.CallOption) (*SendLogRes, error)
}

type logGameClient struct {
	cc grpc.ClientConnInterface
}

func NewLogGameClient(cc grpc.ClientConnInterface) LogGameClient {
	return &logGameClient{cc}
}

func (c *logGameClient) SendLog(ctx context.Context, in *SendLogReq, opts ...grpc.CallOption) (*SendLogRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendLogRes)
	err := c.cc.Invoke(ctx, LogGame_SendLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LogGameServer is the server API for LogGame service.
// All implementations must embed UnimplementedLogGameServer
// for forward compatibility.
type LogGameServer interface {
	SendLog(context.Context, *SendLogReq) (*SendLogRes, error)
	mustEmbedUnimplementedLogGameServer()
}

// UnimplementedLogGameServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLogGameServer struct{}

func (UnimplementedLogGameServer) SendLog(context.Context, *SendLogReq) (*SendLogRes, error) {
	return nil, status.Error(codes.Unimplemented, "method SendLog not implemented")
}
func (UnimplementedLogGameServer) mustEmbedUnimplementedLogGameServer() {}
func (UnimplementedLogGameServer) testEmbeddedByValue()                 {}

// UnsafeLogGameServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LogGameServer will
// result in compilation errors.
type UnsafeLogGameServer interface {
	mustEmbedUnimplementedLogGameServer()
}

func RegisterLogGameServer(s grpc.ServiceRegistrar, srv LogGameServer) {
	// If the following call panics, it indicates UnimplementedLogGameServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LogGame_ServiceDesc, srv)
}

func _LogGame_SendLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendLogReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogGameServer).SendLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogGame_SendLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogGameServer).SendLog(ctx, req.(*SendLogReq))
	}
	return interceptor(ctx, in, info, handler)
}

// LogGame_ServiceDesc is the grpc.ServiceDesc for LogGame service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LogGame_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "log_game.v1.LogGame",
	HandlerType: (*LogGameServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendLog",
			Handler:    _LogGame_SendLog_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "log_game/v1/log_game.proto",
}
