// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package login

import (
	"github.com/gogf/gf/v2/net/gsvc"
	"github.com/gogf/gf/v2/os/gctx"
)

var (
	serviceGsvc gsvc.Service
)

func init() {
	// 1. 获取服务
	serviceGsvc, _ = gsvc.Get(gctx.New(), "game_user")
}
