// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package room

import (
	"web/api/room"
)

type ControllerV1 struct{}

func NewV1() room.IRoomV1 {
	return &ControllerV1{}
}
