// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"game_user/internal/dao/internal"
)

// setGameDao is the data access object for the table set_game.
// You can define custom methods on it to extend its functionality as needed.
type setGameDao struct {
	*internal.SetGameDao
}

var (
	// SetGame is a globally accessible object for table set_game operations.
	SetGame = setGameDao{internal.NewSetGameDao()}
)

// Add your custom methods and functionality below.
