// protoc --go_out=plugins=grpc:. *.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.9
// source: log_game/v1/log_game.proto

package v1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendLogReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomID        string                 `protobuf:"bytes,1,opt,name=RoomID,proto3" json:"RoomID,omitempty" v:"required"` // v: required
	Type          int32                  `protobuf:"varint,2,opt,name=Type,proto3" json:"Type,omitempty"`
	Status        int32                  `protobuf:"varint,3,opt,name=Status,proto3" json:"Status,omitempty"`
	UserID        string                 `protobuf:"bytes,4,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Point         int64                  `protobuf:"varint,5,opt,name=Point,proto3" json:"Point,omitempty"`
	Action        string                 `protobuf:"bytes,6,opt,name=Action,proto3" json:"Action,omitempty"`
	Remain        string                 `protobuf:"bytes,7,opt,name=Remain,proto3" json:"Remain,omitempty"`
	OutCardIds    string                 `protobuf:"bytes,8,opt,name=OutCardIds,proto3" json:"OutCardIds,omitempty"`
	Text          string                 `protobuf:"bytes,9,opt,name=Text,proto3" json:"Text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendLogReq) Reset() {
	*x = SendLogReq{}
	mi := &file_log_game_v1_log_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendLogReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendLogReq) ProtoMessage() {}

func (x *SendLogReq) ProtoReflect() protoreflect.Message {
	mi := &file_log_game_v1_log_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendLogReq.ProtoReflect.Descriptor instead.
func (*SendLogReq) Descriptor() ([]byte, []int) {
	return file_log_game_v1_log_game_proto_rawDescGZIP(), []int{0}
}

func (x *SendLogReq) GetRoomID() string {
	if x != nil {
		return x.RoomID
	}
	return ""
}

func (x *SendLogReq) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *SendLogReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *SendLogReq) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *SendLogReq) GetPoint() int64 {
	if x != nil {
		return x.Point
	}
	return 0
}

func (x *SendLogReq) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *SendLogReq) GetRemain() string {
	if x != nil {
		return x.Remain
	}
	return ""
}

func (x *SendLogReq) GetOutCardIds() string {
	if x != nil {
		return x.OutCardIds
	}
	return ""
}

func (x *SendLogReq) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type SendLogRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendLogRes) Reset() {
	*x = SendLogRes{}
	mi := &file_log_game_v1_log_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendLogRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendLogRes) ProtoMessage() {}

func (x *SendLogRes) ProtoReflect() protoreflect.Message {
	mi := &file_log_game_v1_log_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendLogRes.ProtoReflect.Descriptor instead.
func (*SendLogRes) Descriptor() ([]byte, []int) {
	return file_log_game_v1_log_game_proto_rawDescGZIP(), []int{1}
}

var File_log_game_v1_log_game_proto protoreflect.FileDescriptor

const file_log_game_v1_log_game_proto_rawDesc = "" +
	"\n" +
	"\x1alog_game/v1/log_game.proto\x12\vlog_game.v1\"\xe2\x01\n" +
	"\n" +
	"SendLogReq\x12\x16\n" +
	"\x06RoomID\x18\x01 \x01(\tR\x06RoomID\x12\x12\n" +
	"\x04Type\x18\x02 \x01(\x05R\x04Type\x12\x16\n" +
	"\x06Status\x18\x03 \x01(\x05R\x06Status\x12\x16\n" +
	"\x06UserID\x18\x04 \x01(\tR\x06UserID\x12\x14\n" +
	"\x05Point\x18\x05 \x01(\x03R\x05Point\x12\x16\n" +
	"\x06Action\x18\x06 \x01(\tR\x06Action\x12\x16\n" +
	"\x06Remain\x18\a \x01(\tR\x06Remain\x12\x1e\n" +
	"\n" +
	"OutCardIds\x18\b \x01(\tR\n" +
	"OutCardIds\x12\x12\n" +
	"\x04Text\x18\t \x01(\tR\x04Text\"\f\n" +
	"\n" +
	"SendLogRes2H\n" +
	"\aLogGame\x12=\n" +
	"\aSendLog\x12\x17.log_game.v1.SendLogReq\x1a\x17.log_game.v1.SendLogRes\"\x00B\x14Z\x12api/log_game/v1;v1b\x06proto3"

var (
	file_log_game_v1_log_game_proto_rawDescOnce sync.Once
	file_log_game_v1_log_game_proto_rawDescData []byte
)

func file_log_game_v1_log_game_proto_rawDescGZIP() []byte {
	file_log_game_v1_log_game_proto_rawDescOnce.Do(func() {
		file_log_game_v1_log_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_log_game_v1_log_game_proto_rawDesc), len(file_log_game_v1_log_game_proto_rawDesc)))
	})
	return file_log_game_v1_log_game_proto_rawDescData
}

var file_log_game_v1_log_game_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_log_game_v1_log_game_proto_goTypes = []any{
	(*SendLogReq)(nil), // 0: log_game.v1.SendLogReq
	(*SendLogRes)(nil), // 1: log_game.v1.SendLogRes
}
var file_log_game_v1_log_game_proto_depIdxs = []int32{
	0, // 0: log_game.v1.LogGame.SendLog:input_type -> log_game.v1.SendLogReq
	1, // 1: log_game.v1.LogGame.SendLog:output_type -> log_game.v1.SendLogRes
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_log_game_v1_log_game_proto_init() }
func file_log_game_v1_log_game_proto_init() {
	if File_log_game_v1_log_game_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_log_game_v1_log_game_proto_rawDesc), len(file_log_game_v1_log_game_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_log_game_v1_log_game_proto_goTypes,
		DependencyIndexes: file_log_game_v1_log_game_proto_depIdxs,
		MessageInfos:      file_log_game_v1_log_game_proto_msgTypes,
	}.Build()
	File_log_game_v1_log_game_proto = out.File
	file_log_game_v1_log_game_proto_goTypes = nil
	file_log_game_v1_log_game_proto_depIdxs = nil
}
