// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package enter

import (
	"context"
	"sync"
	"time"

	"github.com/gogf/gf/v2/database/gredis"
	"github.com/gogf/gf/v2/os/gcache"
	"github.com/gorilla/websocket"
)

var (
	clientCache *gcache.Cache
	cacheCtx    = context.Background()
	// 缓存键常量
	cacheKeyPrefix = "ws:client:"

	// fake *faker.Faker

	err error
)

// 客户端连接结构体
type Client struct {
	conn      *websocket.Conn    // WebSocket 连接
	userName  string             // 用户标识（用于重连）
	heartbeat time.Time          // 最后心跳时间
	pid       int                // 玩家id
	cancel    context.CancelFunc // 添加取消函数
	mutex     sync.RWMutex       // 新增：保护 conn 等字段的并发访问
	closed    int32              // 添加原子关闭标记
	subClient *gredis.Redis      // 订阅客户端
	pubClient *gredis.Redis      // 发布客户端
	sub       gredis.Conn        // 添加：订阅者对象
}

// 全局房间管理器及并发安全锁（核心优化：解决全局资源竞争）
var (
	clients   = make(map[string]*Client)
	clientsMu sync.RWMutex // 保护clients的读写锁
	rmMu      sync.RWMutex // 保护roomManager的读写锁
)

// 推送玩家列表（处理JSON错误）
// 创建一个临时结构体，只包含可序列化的字段
type PlayerDTO struct {
	ID       int    `json:"ID"`
	Name     string `json:"Name"`
	RoomID   string `json:"RoomID"`
	Type     int    `json:"Type"`
	CardNum  int    `json:"CardNum"`
	Point    int64  `json:"Point"`
	UserId   string `json:"UserId"`
	RoomType int    `json:"RoomType"`
	// 只包含需要序列化的字段，排除MsgChan等不可序列化字段
}

type Users struct {
	Id       uint   `json:"id"       orm:"id"       description:"自增ID"`
	Name     string `json:"name"     orm:"name"     description:"用户名称"`
	Password string `json:"password" orm:"password" description:"用户密码"`
	Point    int64  `json:"point"    orm:"point"    description:"用户分数"`
	Token    string `json:"token"    orm:"token"    description:"登录token"`
}

func init() {

	clientCache = gcache.New()
}

// 生成缓存键
func getClientCacheKey(userID string) string {
	return cacheKeyPrefix + userID
}

// 添加客户端到缓存
func addClient(client *Client) error {
	cacheKey := getClientCacheKey(client.userName)
	return clientCache.Set(cacheCtx, cacheKey, client, time.Hour)
}

// 根据userID获取客户端
func getClient(userID string) (*Client, error) {
	cacheKey := getClientCacheKey(userID)

	value, err := clientCache.Get(cacheCtx, cacheKey)
	if err != nil {
		return nil, err
	}

	if value == nil || value.IsNil() {
		return nil, nil // 客户端不存在
	}

	client, ok := value.Val().(*Client)
	if !ok {
		// 类型断言失败，删除无效缓存
		clientCache.Remove(cacheCtx, cacheKey)
		return nil, nil
	}

	return client, nil
}

// 删除客户端
func removeClient(userID string) error {
	cacheKey := getClientCacheKey(userID)
	_, err := clientCache.Remove(cacheCtx, cacheKey)
	return err
}

// 批量删除（用于清理操作）
func removeClients(userIDs []string) error {
	for _, userID := range userIDs {
		if err := removeClient(userID); err != nil {
			return err
		}
	}
	return nil
}
