// protoc --go_out=plugins=grpc:. *.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.9
// source: settle/v1/settle.proto

package v1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendSettleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	UserName      string                 `protobuf:"bytes,2,opt,name=UserName,proto3" json:"UserName,omitempty"`
	Point         int64                  `protobuf:"varint,3,opt,name=Point,proto3" json:"Point,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendSettleReq) Reset() {
	*x = SendSettleReq{}
	mi := &file_settle_v1_settle_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendSettleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendSettleReq) ProtoMessage() {}

func (x *SendSettleReq) ProtoReflect() protoreflect.Message {
	mi := &file_settle_v1_settle_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendSettleReq.ProtoReflect.Descriptor instead.
func (*SendSettleReq) Descriptor() ([]byte, []int) {
	return file_settle_v1_settle_proto_rawDescGZIP(), []int{0}
}

func (x *SendSettleReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SendSettleReq) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *SendSettleReq) GetPoint() int64 {
	if x != nil {
		return x.Point
	}
	return 0
}

type SendSettleRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendSettleRes) Reset() {
	*x = SendSettleRes{}
	mi := &file_settle_v1_settle_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendSettleRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendSettleRes) ProtoMessage() {}

func (x *SendSettleRes) ProtoReflect() protoreflect.Message {
	mi := &file_settle_v1_settle_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendSettleRes.ProtoReflect.Descriptor instead.
func (*SendSettleRes) Descriptor() ([]byte, []int) {
	return file_settle_v1_settle_proto_rawDescGZIP(), []int{1}
}

var File_settle_v1_settle_proto protoreflect.FileDescriptor

const file_settle_v1_settle_proto_rawDesc = "" +
	"\n" +
	"\x16settle/v1/settle.proto\x12\tsettle.v1\"Q\n" +
	"\rSendSettleReq\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x03R\x02Id\x12\x1a\n" +
	"\bUserName\x18\x02 \x01(\tR\bUserName\x12\x14\n" +
	"\x05Point\x18\x03 \x01(\x03R\x05Point\"\x0f\n" +
	"\rSendSettleRes2L\n" +
	"\x06Settle\x12B\n" +
	"\n" +
	"SendSettle\x12\x18.settle.v1.SendSettleReq\x1a\x18.settle.v1.SendSettleRes\"\x00B\x12Z\x10api/settle/v1;v1b\x06proto3"

var (
	file_settle_v1_settle_proto_rawDescOnce sync.Once
	file_settle_v1_settle_proto_rawDescData []byte
)

func file_settle_v1_settle_proto_rawDescGZIP() []byte {
	file_settle_v1_settle_proto_rawDescOnce.Do(func() {
		file_settle_v1_settle_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_settle_v1_settle_proto_rawDesc), len(file_settle_v1_settle_proto_rawDesc)))
	})
	return file_settle_v1_settle_proto_rawDescData
}

var file_settle_v1_settle_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_settle_v1_settle_proto_goTypes = []any{
	(*SendSettleReq)(nil), // 0: settle.v1.SendSettleReq
	(*SendSettleRes)(nil), // 1: settle.v1.SendSettleRes
}
var file_settle_v1_settle_proto_depIdxs = []int32{
	0, // 0: settle.v1.Settle.SendSettle:input_type -> settle.v1.SendSettleReq
	1, // 1: settle.v1.Settle.SendSettle:output_type -> settle.v1.SendSettleRes
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_settle_v1_settle_proto_init() }
func file_settle_v1_settle_proto_init() {
	if File_settle_v1_settle_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_settle_v1_settle_proto_rawDesc), len(file_settle_v1_settle_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_settle_v1_settle_proto_goTypes,
		DependencyIndexes: file_settle_v1_settle_proto_depIdxs,
		MessageInfos:      file_settle_v1_settle_proto_msgTypes,
	}.Build()
	File_settle_v1_settle_proto = out.File
	file_settle_v1_settle_proto_goTypes = nil
	file_settle_v1_settle_proto_depIdxs = nil
}
