// protoc --go_out=plugins=grpc:. *.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.9
// source: settle/v1/settle.proto

package v1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Settle_SendSettle_FullMethodName = "/settle.v1.Settle/SendSettle"
)

// SettleClient is the client API for Settle service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SettleClient interface {
	SendSettle(ctx context.Context, in *SendSettleReq, opts ...grpc.CallOption) (*SendSettleRes, error)
}

type settleClient struct {
	cc grpc.ClientConnInterface
}

func NewSettleClient(cc grpc.ClientConnInterface) SettleClient {
	return &settleClient{cc}
}

func (c *settleClient) SendSettle(ctx context.Context, in *SendSettleReq, opts ...grpc.CallOption) (*SendSettleRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendSettleRes)
	err := c.cc.Invoke(ctx, Settle_SendSettle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SettleServer is the server API for Settle service.
// All implementations must embed UnimplementedSettleServer
// for forward compatibility.
type SettleServer interface {
	SendSettle(context.Context, *SendSettleReq) (*SendSettleRes, error)
	mustEmbedUnimplementedSettleServer()
}

// UnimplementedSettleServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSettleServer struct{}

func (UnimplementedSettleServer) SendSettle(context.Context, *SendSettleReq) (*SendSettleRes, error) {
	return nil, status.Error(codes.Unimplemented, "method SendSettle not implemented")
}
func (UnimplementedSettleServer) mustEmbedUnimplementedSettleServer() {}
func (UnimplementedSettleServer) testEmbeddedByValue()                {}

// UnsafeSettleServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SettleServer will
// result in compilation errors.
type UnsafeSettleServer interface {
	mustEmbedUnimplementedSettleServer()
}

func RegisterSettleServer(s grpc.ServiceRegistrar, srv SettleServer) {
	// If the following call panics, it indicates UnimplementedSettleServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Settle_ServiceDesc, srv)
}

func _Settle_SendSettle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendSettleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettleServer).SendSettle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Settle_SendSettle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettleServer).SendSettle(ctx, req.(*SendSettleReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Settle_ServiceDesc is the grpc.ServiceDesc for Settle service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Settle_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "settle.v1.Settle",
	HandlerType: (*SettleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendSettle",
			Handler:    _Settle_SendSettle_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "settle/v1/settle.proto",
}
