// protoc --go_out=plugins=grpc:. *.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.9
// source: set.proto

package v1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendSetReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty" v:"required"`     // v: required
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty" v:"required"` // v: required
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendSetReq) Reset() {
	*x = SendSetReq{}
	mi := &file_set_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendSetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendSetReq) ProtoMessage() {}

func (x *SendSetReq) ProtoReflect() protoreflect.Message {
	mi := &file_set_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendSetReq.ProtoReflect.Descriptor instead.
func (*SendSetReq) Descriptor() ([]byte, []int) {
	return file_set_proto_rawDescGZIP(), []int{0}
}

func (x *SendSetReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SendSetReq) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type SendSetRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendSetRes) Reset() {
	*x = SendSetRes{}
	mi := &file_set_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendSetRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendSetRes) ProtoMessage() {}

func (x *SendSetRes) ProtoReflect() protoreflect.Message {
	mi := &file_set_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendSetRes.ProtoReflect.Descriptor instead.
func (*SendSetRes) Descriptor() ([]byte, []int) {
	return file_set_proto_rawDescGZIP(), []int{1}
}

var File_set_proto protoreflect.FileDescriptor

const file_set_proto_rawDesc = "" +
	"\n" +
	"\tset.proto\x12\vset_game.v1\"4\n" +
	"\n" +
	"SendSetReq\x12\x10\n" +
	"\x03Key\x18\x01 \x01(\tR\x03Key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\f\n" +
	"\n" +
	"SendSetRes2H\n" +
	"\aSetGame\x12=\n" +
	"\aSendSet\x12\x17.set_game.v1.SendSetReq\x1a\x17.set_game.v1.SendSetRes\"\x00B\x14Z\x12api/set_game/v1;v1b\x06proto3"

var (
	file_set_proto_rawDescOnce sync.Once
	file_set_proto_rawDescData []byte
)

func file_set_proto_rawDescGZIP() []byte {
	file_set_proto_rawDescOnce.Do(func() {
		file_set_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_set_proto_rawDesc), len(file_set_proto_rawDesc)))
	})
	return file_set_proto_rawDescData
}

var file_set_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_set_proto_goTypes = []any{
	(*SendSetReq)(nil), // 0: set_game.v1.SendSetReq
	(*SendSetRes)(nil), // 1: set_game.v1.SendSetRes
}
var file_set_proto_depIdxs = []int32{
	0, // 0: set_game.v1.SetGame.SendSet:input_type -> set_game.v1.SendSetReq
	1, // 1: set_game.v1.SetGame.SendSet:output_type -> set_game.v1.SendSetRes
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_set_proto_init() }
func file_set_proto_init() {
	if File_set_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_set_proto_rawDesc), len(file_set_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_set_proto_goTypes,
		DependencyIndexes: file_set_proto_depIdxs,
		MessageInfos:      file_set_proto_msgTypes,
	}.Build()
	File_set_proto = out.File
	file_set_proto_goTypes = nil
	file_set_proto_depIdxs = nil
}
