// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gfast/internal/app/log/dao/internal"
)

// logGameDao is the data access object for the table log_game.
// You can define custom methods on it to extend its functionality as needed.
type logGameDao struct {
	*internal.LogGameDao
}

var (
	// LogGame is a globally accessible object for table log_game operations.
	LogGame = logGameDao{internal.NewLogGameDao()}
)

// Add your custom methods and functionality below.
