// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package logic

import (
	_ "gfast/internal/app/common/logic/cache"
	_ "gfast/internal/app/common/logic/captcha"
	_ "gfast/internal/app/common/logic/eventBus"
	_ "gfast/internal/app/common/logic/middleware"
	_ "gfast/internal/app/common/logic/sysConfig"
	_ "gfast/internal/app/common/logic/sysDictData"
	_ "gfast/internal/app/common/logic/sysDictType"
)
